apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: faez
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - env:
        - name: POC
          value: POC
        image: quay.io/redhat-appstudio-qe/byoc-mnsw-tenant/byoc-app-oyzj/faez@sha256:32c83547a4be91c7be84122b65c8510f52fb803c76fed63341f745f37868a317
        name: my-java-quarkus
        resources: {}
status: {}
