apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: faez
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: faez
    app.kubernetes.io/part-of: byoc-app-oyzj
  name: faez
spec:
  rules:
  - host: faez-byoc-mnsw-tenant.apps.446ab93cc463e258ec0d.hypershift.aws-2.ci.openshift.org
    http:
      paths:
      - backend:
          service:
            name: faez
            port:
              number: 8081
        path: /
        pathType: ImplementationSpecific
status:
  loadBalancer: {}
